
country_choices = [
    ("Afghanistan", "Afghanistan"),
    ("Åland Islands", "Åland Islands"),
    ("Albania", "Albania"),
    ("Algeria", "Algeria"),
    ("American Samoa", "American Samoa"),
    ("Andorra", "Andorra"),
    ("Angola", "Angola"),
    ("Anguilla", "Anguilla"),
    ("Antarctica", "Antarctica"),
    ("Antigua and Barbuda", "Antigua and Barbuda"),
    ("Argentina", "Argentina"),
    ("Armenia", "Armenia"),
    ("Aruba", "Aruba"),
    ("Australia", "Australia"),
    ("Austria", "Austria"),
    ("Azerbaijan", "Azerbaijan"),
    ("Bahamas", "Bahamas"),
    ("Bahrain", "Bahrain"),
    ("Bangladesh", "Bangladesh"),
    ("Barbados", "Barbados"),
    ("Belarus", "Belarus"),
    ("Belgium", "Belgium"),
    ("Belize", "Belize"),
    ("Benin", "Benin"),
    ("Bermuda", "Bermuda"),
    ("Bhutan", "Bhutan"),
    ("Bolivia", "Bolivia"),
    ("Bosnia and Herzegovina", "Bosnia and Herzegovina"),
    ("Botswana", "Botswana"),
    ("Bouvet Island", "Bouvet Island"),
    ("Brazil", "Brazil"),
    ("British Indian Ocean Territory", "British Indian Ocean Territory"),
    ("Brunei Darussalam", "Brunei Darussalam"),
    ("Bulgaria", "Bulgaria"),
    ("Burkina Faso", "Burkina Faso"),
    ("Burundi", "Burundi"),
    ("Cambodia", "Cambodia"),
    ("Cameroon", "Cameroon"),
    ("Canada", "Canada"),
    ("Cape Verde", "Cape Verde"),
    ("Cayman Islands", "Cayman Islands"),
    ("Central African Republic", "Central African Republic"),
    ("Chad", "Chad"),
    ("Chile", "Chile"),
    ("China", "China"),
    ("Christmas Island", "Christmas Island"),
    ("Cocos (Keeling) Islands", "Cocos (Keeling) Islands"),
    ("Colombia", "Colombia"),
    ("Comoros", "Comoros"),
    ("Congo", "Congo"),
    ("Congo, The Democratic Republic of The", "Congo, The Democratic Republic of The"),
    ("Cook Islands", "Cook Islands"),
    ("Costa Rica", "Costa Rica"),
    ("Cote D'ivoire", "Cote D'ivoire"),
    ("Croatia", "Croatia"),
    ("Cuba", "Cuba"),
    ("Cyprus", "Cyprus"),
    ("Czech Republic", "Czech Republic"),
    ("Denmark", "Denmark"),
    ("Djibouti", "Djibouti"),
    ("Dominica", "Dominica"),
    ("Dominican Republic", "Dominican Republic"),
    ("Ecuador", "Ecuador"),
    ("Egypt", "Egypt"),
    ("El Salvador", "El Salvador"),
    ("Equatorial Guinea", "Equatorial Guinea"),
    ("Eritrea", "Eritrea"),
    ("Estonia", "Estonia"),
    ("Ethiopia", "Ethiopia"),
    ("Falkland Islands (Malvinas)", "Falkland Islands (Malvinas)"),
    ("Faroe Islands", "Faroe Islands"),
    ("Fiji", "Fiji"),
    ("Finland", "Finland"),
    ("France", "France"),
    ("French Guiana", "French Guiana"),
    ("French Polynesia", "French Polynesia"),
    ("French Southern Territories", "French Southern Territories"),
    ("Gabon", "Gabon"),
    ("Gambia", "Gambia"),
    ("Georgia", "Georgia"),
    ("Germany", "Germany"),
    ("Ghana", "Ghana"),
    ("Gibraltar", "Gibraltar"),
    ("Greece", "Greece"),
    ("Greenland", "Greenland"),
    ("Grenada", "Grenada"),
    ("Guadeloupe", "Guadeloupe"),
    ("Guam", "Guam"),
    ("Guatemala", "Guatemala"),
    ("Guernsey", "Guernsey"),
    ("Guinea", "Guinea"),
    ("Guinea-bissau", "Guinea-bissau"),
    ("Guyana", "Guyana"),
    ("Haiti", "Haiti"),
    ("Heard Island and Mcdonald Islands", "Heard Island and Mcdonald Islands"),
    ("Holy See (Vatican City State)", "Holy See (Vatican City State)"),
    ("Honduras", "Honduras"),
    ("Hong Kong", "Hong Kong"),
    ("Hungary", "Hungary"),
    ("Iceland", "Iceland"),
    ("India", "India"),
    ("Indonesia", "Indonesia"),
    ("Iran, Islamic Republic of", "Iran, Islamic Republic of"),
    ("Iraq", "Iraq"),
    ("Ireland", "Ireland"),
    ("Isle of Man", "Isle of Man"),
    ("Israel", "Israel"),
    ("Italy", "Italy"),
    ("Jamaica", "Jamaica"),
    ("Japan", "Japan"),
    ("Jersey", "Jersey"),
    ("Jordan", "Jordan"),
    ("Kazakhstan", "Kazakhstan"),
    ("Kenya", "Kenya"),
    ("Kiribati", "Kiribati"),
    ("Korea, Democratic People's Republic of", "Korea, Democratic People's Republic of"),
    ("Korea, Republic of", "Korea, Republic of"),
    ("Kuwait", "Kuwait"),
    ("Kyrgyzstan", "Kyrgyzstan"),
    ("Lao People's Democratic Republic", "Lao People's Democratic Republic"),
    ("Latvia", "Latvia"),
    ("Lebanon", "Lebanon"),
    ("Lesotho", "Lesotho"),
    ("Liberia", "Liberia"),
    ("Libyan Arab Jamahiriya", "Libyan Arab Jamahiriya"),
    ("Liechtenstein", "Liechtenstein"),
    ("Lithuania", "Lithuania"),
    ("Luxembourg", "Luxembourg"),
    ("Macao", "Macao"),
    ("Macedonia, The Former Yugoslav Republic of", "Macedonia, The Former Yugoslav Republic of"),
    ("Madagascar", "Madagascar"),
    ("Malawi", "Malawi"),
    ("Malaysia", "Malaysia"),
    ("Maldives", "Maldives"),
    ("Mali", "Mali"),
    ("Malta", "Malta"),
    ("Marshall Islands", "Marshall Islands"),
    ("Martinique", "Martinique"),
    ("Mauritania", "Mauritania"),
    ("Mauritius", "Mauritius"),
    ("Mayotte", "Mayotte"),
    ("Mexico", "Mexico"),
    ("Micronesia, Federated States of", "Micronesia, Federated States of"),
    ("Moldova, Republic of", "Moldova, Republic of"),
    ("Monaco", "Monaco"),
    ("Mongolia", "Mongolia"),
    ("Montenegro", "Montenegro"),
    ("Montserrat", "Montserrat"),
    ("Morocco", "Morocco"),
    ("Mozambique", "Mozambique"),
    ("Myanmar", "Myanmar"),
    ("Namibia", "Namibia"),
    ("Nauru", "Nauru"),
    ("Nepal", "Nepal"),
    ("Netherlands", "Netherlands"),
    ("Netherlands Antilles", "Netherlands Antilles"),
    ("New Caledonia", "New Caledonia"),
    ("New Zealand", "New Zealand"),
    ("Nicaragua", "Nicaragua"),
    ("Niger", "Niger"),
    ("Nigeria", "Nigeria"),
    ("Niue", "Niue"),
    ("Norfolk Island", "Norfolk Island"),
    ("Northern Mariana Islands", "Northern Mariana Islands"),
    ("Norway", "Norway"),
    ("Oman", "Oman"),
    ("Pakistan", "Pakistan"),
    ("Palau", "Palau"),
    ("Palestinian Territory, Occupied", "Palestinian Territory, Occupied"),
    ("Panama", "Panama"),
    ("Papua New Guinea", "Papua New Guinea"),
    ("Paraguay", "Paraguay"),
    ("Peru", "Peru"),
    ("Philippines", "Philippines"),
    ("Pitcairn", "Pitcairn"),
    ("Poland", "Poland"),
    ("Portugal", "Portugal"),
    ("Puerto Rico", "Puerto Rico"),
    ("Qatar", "Qatar"),
    ("Reunion", "Reunion"),
    ("Romania", "Romania"),
    ("Russian Federation", "Russian Federation"),
    ("Rwanda", "Rwanda"),
    ("Saint Helena", "Saint Helena"),
    ("Saint Kitts and Nevis", "Saint Kitts and Nevis"),
    ("Saint Lucia", "Saint Lucia"),
    ("Saint Pierre and Miquelon", "Saint Pierre and Miquelon"),
    ("Saint Vincent and The Grenadines", "Saint Vincent and The Grenadines"),
    ("Samoa", "Samoa"),
    ("San Marino", "San Marino"),
    ("Sao Tome and Principe", "Sao Tome and Principe"),
    ("Saudi Arabia", "Saudi Arabia"),
    ("Senegal", "Senegal"),
    ("Serbia", "Serbia"),
    ("Seychelles", "Seychelles"),
    ("Sierra Leone", "Sierra Leone"),
    ("Singapore", "Singapore"),
    ("Slovakia", "Slovakia"),
    ("Slovenia", "Slovenia"),
    ("Solomon Islands", "Solomon Islands"),
    ("Somalia", "Somalia"),
    ("South Africa", "South Africa"),
    ("South Georgia and The South Sandwich Islands", "South Georgia and The South Sandwich Islands"),
    ("Spain", "Spain"),
    ("Sri Lanka", "Sri Lanka"),
    ("Sudan", "Sudan"),
    ("Suriname", "Suriname"),
    ("Svalbard and Jan Mayen", "Svalbard and Jan Mayen"),
    ("Swaziland", "Swaziland"),
    ("Sweden", "Sweden"),
    ("Switzerland", "Switzerland"),
    ("Syrian Arab Republic", "Syrian Arab Republic"),
    ("Taiwan", "Taiwan"),
    ("Tajikistan", "Tajikistan"),
    ("Tanzania, United Republic of", "Tanzania, United Republic of"),
    ("Thailand", "Thailand"),
    ("Timor-leste", "Timor-leste"),
    ("Togo", "Togo"),
    ("Tokelau", "Tokelau"),
    ("Tonga", "Tonga"),
    ("Trinidad and Tobago", "Trinidad and Tobago"),
    ("Tunisia", "Tunisia"),
    ("Turkey", "Turkey"),
    ("Turkmenistan", "Turkmenistan"),
    ("Turks and Caicos Islands", "Turks and Caicos Islands"),
    ("Tuvalu", "Tuvalu"),
    ("Uganda", "Uganda"),
    ("Ukraine", "Ukraine"),
    ("United Arab Emirates", "United Arab Emirates"),
    ("United Kingdom", "United Kingdom"),
    ("United States", "United States"),
    ("United States Minor Outlying Islands", "United States Minor Outlying Islands"),
    ("Uruguay", "Uruguay"),
    ("Uzbekistan", "Uzbekistan"),
    ("Vanuatu", "Vanuatu"),
    ("Venezuela", "Venezuela"),
    ("Viet Nam", "Viet Nam"),
    ("Virgin Islands, British", "Virgin Islands, British"),
    ("Virgin Islands, U.S.", "Virgin Islands, U.S."),
    ("Wallis and Futuna", "Wallis and Futuna"),
    ("Western Sahara", "Western Sahara"),
    ("Yemen", "Yemen"),
    ("Zambia", "Zambia"),
    ("Zimbabwe", "Zimbabwe"),
]

country_code_choices = [
    ("Algeria (+213)", "Algeria (+213)"),
    ("Andorra (+376)", "Andorra (+376)"),
    ("Angola (+244)", "Angola (+244)"),
    ("Anguilla (+1264)", "Anguilla (+1264)"),
    ("Antigua & Barbuda (+1268)", "Antigua & Barbuda (+1268)"),
    ("Argentina (+54)", "Argentina (+54)"),
    ("Armenia (+374)", "Armenia (+374)"),
    ("Aruba (+297)", "Aruba (+297)"),
    ("Australia (+61)", "Australia (+61)"),
    ("Austria (+43)", "Austria (+43)"),
    ("Azerbaijan (+994)", "Azerbaijan (+994)"),
    ("Bahamas (+1242)", "Bahamas (+1242)"),
    ("Bahrain (+973)", "Bahrain (+973)"),
    ("Bangladesh (+880)", "Bangladesh (+880)"),
    ("Barbados (+1246)", "Barbados (+1246)"),
    ("Belarus (+375)", "Belarus (+375)"),
    ("Belgium (+32)", "Belgium (+32)"),
    ("Belize (+501)", "Belize (+501)"),
    ("Benin (+229)", "Benin (+229)"),
    ("Bermuda (+1441)", "Bermuda (+1441)"),
    ("Bhutan (+975)", "Bhutan (+975)"),
    ("Bolivia (+591)", "Bolivia (+591)"),
    ("Bosnia Herzegovina (+387)", "Bosnia Herzegovina (+387)"),
    ("Botswana (+267)", "Botswana (+267)"),
    ("Brazil (+55)", "Brazil (+55)"),
    ("Brunei (+673)", "Brunei (+673)"),
    ("Bulgaria (+359)", "Bulgaria (+359)"),
    ("Burkina Faso (+226)", "Burkina Faso (+226)"),
    ("Burundi (+257)", "Burundi (+257)"),
    ("Cambodia (+855)", "Cambodia (+855)"),
    ("Cameroon (+237)", "Cameroon (+237)"),
    ("Canada (+1)", "Canada (+1)"),
    ("Cape Verde Islands (+238)", "Cape Verde Islands (+238)"),
    ("Cayman Islands (+1345)", "Cayman Islands (+1345)"),
    ("Central African Republic (+236)", "Central African Republic (+236)"),
    ("Chile (+56)", "Chile (+56)"),
    ("China (+86)", "China (+86)"),
    ("Colombia (+57)", "Colombia (+57)"),
    ("Comoros (+269)", "Comoros (+269)"),
    ("Congo (+242)", "Congo (+242)"),
    ("Cook Islands (+682)", "Cook Islands (+682)"),
    ("Costa Rica (+506)", "Costa Rica (+506)"),
    ("Croatia (+385)", "Croatia (+385)"),
    ("Cuba (+53)", "Cuba (+53)"),
    ("Cyprus North (+90392)", "Cyprus North (+90392)"),
    ("Cyprus South (+357)", "Cyprus South (+357)"),
    ("Czech Republic (+42)", "Czech Republic (+42)"),
    ("Denmark (+45)", "Denmark (+45)"),
    ("Djibouti (+253)", "Djibouti (+253)"),
    ("Dominica (+1809)", "Dominica (+1809)"),
    ("Dominican Republic (+1809)", "Dominican Republic (+1809)"),
    ("Ecuador (+593)", "Ecuador (+593)"),
    ("Egypt (+20)", "Egypt (+20)"),
    ("El Salvador (+503)", "El Salvador (+503)"),
    ("Equatorial Guinea (+240)", "Equatorial Guinea (+240)"),
    ("Eritrea (+291)", "Eritrea (+291)"),
    ("Estonia (+372)", "Estonia (+372)"),
    ("Ethiopia (+251)", "Ethiopia (+251)"),
    ("Falkland Islands (+500)", "Falkland Islands (+500)"),
    ("Faroe Islands (+298)", "Faroe Islands (+298)"),
    ("Fiji (+679)", "Fiji (+679)"),
    ("Finland (+358)", "Finland (+358)"),
    ("France (+33)", "France (+33)"),
    ("French Guiana (+594)", "French Guiana (+594)"),
    ("French Polynesia (+689)", "French Polynesia (+689)"),
    ("Gabon (+241)", "Gabon (+241)"),
    ("Gambia (+220)", "Gambia (+220)"),
    ("Georgia (+7880)", "Georgia (+7880)"),
    ("Germany (+49)", "Germany (+49)"),
    ("Ghana (+233)", "Ghana (+233)"),
    ("Gibraltar (+350)", "Gibraltar (+350)"),
    ("Greece (+30)", "Greece (+30)"),
    ("Greenland (+299)", "Greenland (+299)"),
    ("Grenada (+1473)", "Grenada (+1473)"),
    ("Guadeloupe (+590)", "Guadeloupe (+590)"),
    ("Guam (+671)", "Guam (+671)"),
    ("Guatemala (+502)", "Guatemala (+502)"),
    ("Guinea (+224)", "Guinea (+224)"),
    ("Guinea - Bissau (+245)", "Guinea - Bissau (+245)"),
    ("Guyana (+592)", "Guyana (+592)"),
    ("Haiti (+509)", "Haiti (+509)"),
    ("Honduras (+504)", "Honduras (+504)"),
    ("Hong Kong (+852)", "Hong Kong (+852)"),
    ("Hungary (+36)", "Hungary (+36)"),
    ("Iceland (+354)", "Iceland (+354)"),
    ("India (+91)", "India (+91)"),
    ("Indonesia (+62)", "Indonesia (+62)"),
    ("Iran (+98)", "Iran (+98)"),
    ("Iraq (+964)", "Iraq (+964)"),
    ("Ireland (+353)", "Ireland (+353)"),
    ("Israel (+972)", "Israel (+972)"),
    ("Italy (+39)", "Italy (+39)"),
    ("Jamaica (+1876)", "Jamaica (+1876)"),
    ("Japan (+81)", "Japan (+81)"),
    ("Jordan (+962)", "Jordan (+962)"),
    ("Kazakhstan (+7)", "Kazakhstan (+7)"),
    ("Kenya (+254)", "Kenya (+254)"),
    ("Kiribati (+686)", "Kiribati (+686)"),
    ("Korea North (+850)", "Korea North (+850)"),
    ("Korea South (+82)", "Korea South (+82)"),
    ("Kuwait (+965)", "Kuwait (+965)"),
    ("Kyrgyzstan (+996)", "Kyrgyzstan (+996)"),
    ("Laos (+856)", "Laos (+856)"),
    ("Latvia (+371)", "Latvia (+371)"),
    ("Lebanon (+961)", "Lebanon (+961)"),
    ("Lesotho (+266)", "Lesotho (+266)"),
    ("Liberia (+231)", "Liberia (+231)"),
    ("Libya (+218)", "Libya (+218)"),
    ("Liechtenstein (+417)", "Liechtenstein (+417)"),
    ("Lithuania (+370)", "Lithuania (+370)"),
    ("Luxembourg (+352)", "Luxembourg (+352)"),
    ("Macao (+853)", "Macao (+853)"),
    ("Macedonia (+389)", "Macedonia (+389)"),
    ("Madagascar (+261)", "Madagascar (+261)"),
    ("Malawi (+265)", "Malawi (+265)"),
    ("Malaysia (+60)", "Malaysia (+60)"),
    ("Maldives (+960)", "Maldives (+960)"),
    ("Mali (+223)", "Mali (+223)"),
    ("Malta (+356)", "Malta (+356)"),
    ("Marshall Islands (+692)", "Marshall Islands (+692)"),
    ("Martinique (+596)", "Martinique (+596)"),
    ("Mauritania (+222)", "Mauritania (+222)"),
    ("Mayotte (+269)", "Mayotte (+269)"),
    ("Mexico (+52)", "Mexico (+52)"),
    ("Micronesia (+691)", "Micronesia (+691)"),
    ("Moldova (+373)", "Moldova (+373)"),
    ("Monaco (+377)", "Monaco (+377)"),
    ("Mongolia (+976)", "Mongolia (+976)"),
    ("Montserrat (+1664)", "Montserrat (+1664)"),
    ("Morocco (+212)", "Morocco (+212)"),
    ("Mozambique (+258)", "Mozambique (+258)"),
    ("Myanmar (+95)", "Myanmar (+95)"),
    ("Namibia (+264)", "Namibia (+264)"),
    ("Nauru (+674)", "Nauru (+674)"),
    ("Nepal (+977)", "Nepal (+977)"),
    ("Netherlands (+31)", "Netherlands (+31)"),
    ("New Caledonia (+687)", "New Caledonia (+687)"),
    ("New Zealand (+64)", "New Zealand (+64)"),
    ("Nicaragua (+505)", "Nicaragua (+505)"),
    ("Niger (+227)", "Niger (+227)"),
    ("Nigeria (+234)", "Nigeria (+234)"),
    ("Niue (+683)", "Niue (+683)"),
    ("Norfolk Islands (+672)", "Norfolk Islands (+672)"),
    ("Northern Marianas (+670)", "Northern Marianas (+670)"),
    ("Norway (+47)", "Norway (+47)"),
    ("Oman (+968)", "Oman (+968)"),
    ("Pakistan (+92)", "Pakistan (+92)"),
    ("Palau (+680)", "Palau (+680)"),
    ("Panama (+507)", "Panama (+507)"),
    ("Papua New Guinea (+675)", "Papua New Guinea (+675)"),
    ("Paraguay (+595)", "Paraguay (+595)"),
    ("Peru (+51)", "Peru (+51)"),
    ("Philippines (+63)", "Philippines (+63)"),
    ("Poland (+48)", "Poland (+48)"),
    ("Portugal (+351)", "Portugal (+351)"),
    ("Puerto Rico (+1787)", "Puerto Rico (+1787)"),
    ("Qatar (+974)", "Qatar (+974)"),
    ("Reunion (+262)", "Reunion (+262)"),
    ("Romania (+40)", "Romania (+40)"),
    ("Russia (+7)", "Russia (+7)"),
    ("Rwanda (+250)", "Rwanda (+250)"),
    ("San Marino (+378)", "San Marino (+378)"),
    ("Sao Tome & Principe (+239)", "Sao Tome & Principe (+239)"),
    ("Saudi Arabia (+966)", "Saudi Arabia (+966)"),
    ("Senegal (+221)", "Senegal (+221)"),
    ("Serbia (+381)", "Serbia (+381)"),
    ("Seychelles (+248)", "Seychelles (+248)"),
    ("Sierra Leone (+232)", "Sierra Leone (+232)"),
    ("Singapore (+65)", "Singapore (+65)"),
    ("Slovak Republic (+421)", "Slovak Republic (+421)"),
    ("Slovenia (+386)", "Slovenia (+386)"),
    ("Solomon Islands (+677)", "Solomon Islands (+677)"),
    ("Somalia (+252)", "Somalia (+252)"),
    ("South Africa (+27)", "South Africa (+27)"),
    ("Spain (+34)", "Spain (+34)"),
    ("Sri Lanka (+94)", "Sri Lanka (+94)"),
    ("St. Helena (+290)", "St. Helena (+290)"),
    ("St. Kitts (+1869)", "St. Kitts (+1869)"),
    ("St. Lucia (+1758)", "St. Lucia (+1758)"),
    ("Sudan (+249)", "Sudan (+249)"),
    ("Suriname (+597)", "Suriname (+597)"),
    ("Swaziland (+268)", "Swaziland (+268)"),
    ("Sweden (+46)", "Sweden (+46)"),
    ("Switzerland (+41)", "Switzerland (+41)"),
    ("Syria (+963)", "Syria (+963)"),
    ("Taiwan (+886)", "Taiwan (+886)"),
    ("Tajikstan (+7)", "Tajikstan (+7)"),
    ("Thailand (+66)", "Thailand (+66)"),
    ("Togo (+228)", "Togo (+228)"),
    ("Tonga (+676)", "Tonga (+676)"),
    ("Trinidad & Tobago (+1868)", "Trinidad & Tobago (+1868)"),
    ("Tunisia (+216)", "Tunisia (+216)"),
    ("Turkey (+90)", "Turkey (+90)"),
    ("Turkmenistan (+7)", "Turkmenistan (+7)"),
    ("Turks & Caicos Islands (+1649)", "Turks & Caicos Islands (+1649)"),
    ("Tuvalu (+688)", "Tuvalu (+688)"),
    ("Uganda (+256)", "Uganda (+256)"),
    ("UK (+44)", "UK (+44)"),
    ("Ukraine (+380)", "Ukraine (+380)"),
    ("United Arab Emirates (+971)", "United Arab Emirates (+971)"),
    ("Uruguay (+598)", "Uruguay (+598)"),
    ("Uzbekistan (+7)", "Uzbekistan (+7)"),
    ("Vanuatu (+678)", "Vanuatu (+678)"),
    ("Vatican City (+379)", "Vatican City (+379)"),
    ("Venezuela (+58)", "Venezuela (+58)"),
    ("Vietnam (+84)", "Vietnam (+84)"),
    ("Virgin Islands - British (+1284)", "Virgin Islands - British (+1284)"),
    ("Virgin Islands - US (+1340)", "Virgin Islands - US (+1340)"),
    ("Wallis & Futuna (+681)", "Wallis & Futuna (+681)"),
    ("Yemen (North)(+969)", "Yemen (North)(+969)"),
    ("Yemen (South)(+967)", "Yemen (South)(+967)"),
    ("Zambia (+260)", "Zambia (+260)"),
    ("Zimbabwe (+263)", "Zimbabwe (+263)")
]
